db_name: "pocket_bot"

bot_url: "https://t.me/pocket91233bot"

message:
  response:
    start: "Привет! Чтобы сохранять ссылки в своем Pocket аккаунте, для начала тебе необходимо дать мне на это доступ. Для этого перейди по ссылке:\n%s"
    help: "Скинь мне ссылку, а я добавлю ее в Pocket"
    already_authorized: "Ты уже авторизирован. Присылай ссылку, а ее сохраню"
    saves_successfully: "Ссылка успешно сохранена!"
    unknow_command: "Я не знаю такой команды :("
  error:
    default: "Неизвестная ошибка"
    invalid_url: "Это не валидная ссылка"
    unauthorized: "Ты не авторизировался"
    unable_to_save: "Не получилось сохранить ссылку, попробуй позже"